version: '3'

services:
    web_server:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:80"
        restart: always
        volumes:
            - ./index.php:/var/www/html/index.php
            - ./style.css:/var/www/html/style.css
        links:
            - db
    db:
        platform: linux/x86_64
        image: mysql:5.7
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: text
            MYSQL_USER: User
            MYSQL_PASSWORD: 123456789

volumes:
    db_data: